/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-06-10 at 15:16:38 UTC 
 * Modify at your own risk.
 */

package at.software2014.trackme.userdataendpoint.model;

/**
 * Model definition for UserData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userdataendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> allowedUsersForQuerying;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long timestamp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userEmail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double userLastLatitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double userLastLongitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userName;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getAllowedUsersForQuerying() {
    return allowedUsersForQuerying;
  }

  /**
   * @param allowedUsersForQuerying allowedUsersForQuerying or {@code null} for none
   */
  public UserData setAllowedUsersForQuerying(java.util.List<java.lang.String> allowedUsersForQuerying) {
    this.allowedUsersForQuerying = allowedUsersForQuerying;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * @param timestamp timestamp or {@code null} for none
   */
  public UserData setTimestamp(java.lang.Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserEmail() {
    return userEmail;
  }

  /**
   * @param userEmail userEmail or {@code null} for none
   */
  public UserData setUserEmail(java.lang.String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getUserLastLatitude() {
    return userLastLatitude;
  }

  /**
   * @param userLastLatitude userLastLatitude or {@code null} for none
   */
  public UserData setUserLastLatitude(java.lang.Double userLastLatitude) {
    this.userLastLatitude = userLastLatitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getUserLastLongitude() {
    return userLastLongitude;
  }

  /**
   * @param userLastLongitude userLastLongitude or {@code null} for none
   */
  public UserData setUserLastLongitude(java.lang.Double userLastLongitude) {
    this.userLastLongitude = userLastLongitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public UserData setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  @Override
  public UserData set(String fieldName, Object value) {
    return (UserData) super.set(fieldName, value);
  }

  @Override
  public UserData clone() {
    return (UserData) super.clone();
  }

}
